### PR TITLE
About page

### LINKED ISSUE #16: About Page
# Description

A page of details about:

- contributors linking to their preferred profiles
- versions
- dependencies

## Sub Tasks

- [ ] Do This
- [ ] Do That

### PR DESCRIPTION
**Pull request by Depechie**
Initial draft PR to show off potential About page design

- [x] Show info about the app itself in general area
- [x] Show list of contributors
- [x] Navigate to contributor profile on GitHub when selected
- [ ] Loading animation?
- [ ] Pull to refresh?

Fixes #16 

Current preview:
Screenshot 2019-05-03 at 00 52 52

### CODE REVIEW

**Comment by davidortinau** [comment]
@pureween, look at the image above ^. I know you addressed the SafeArea / padding type situation for the header. Does the fix also account for the top tab bar? This is pre9.

**Comment by PureWeen** [comment]
Yes it should

**Comment by PureWeen** [comment]
Here's this if you want to try it out and see if it resolves it

[Xamarin.Forms.4.0.0.388654-pre10.zip](https://github.com/davidortinau/Xappy/files/3140559/Xamarin.Forms.4.0.0.388654-pre10.zip)

**Comment by Depechie** [comment]
So @davidortinau will you add this pre10 to the Master branch? That way I can take it over on my Fork > Branch

**Comment by davidortinau** [comment]
@Depechie pre10 is now in master.

**Comment by Depechie** [comment]
@PureWeen if pre10 is applied, do I still need to provide some code to get this going? Default rendering does not fix this.
Also tried applying UseSafeArea="true" with no luck.

**Comment by Depechie** [comment]
@davidortinau this can be merged now...

**Review by davidortinau — APPROVED** [review]

**Pull request merged**
