### PR TITLE
product details and themes

### PR DESCRIPTION
**Pull request by davidortinau**
New scenario for product details with parallax and xamanimations. Style guide and light/dark themes.

### CODE REVIEW

**Comment by farr64** [comment]
Unable to find package Xamarin.Forms with version (>= 4.3.0.930-nightly)
  - Found 234 version(s) in nuget.org [ Nearest version: 4.1.0.581479 ]
Unable to find package Xamarin.Forms.Maps with version (>= 4.3.0.930-nightly)
  - Found 231 version(s) in nuget.org [ Nearest version: 4.1.0.581479 ]
Unable to find package Xamarin.Forms.Visual.Material with version (>= 4.3.0.930-nightly)
  - Found 26 version(s) in nuget.org [ Nearest version: 4.1.0.581479 ]
Package restore failed. Rolling back package changes for 'Xappy.Android'.


Any suggestions?

Thanks.

**Comment by davidortinau** [comment]
You’ll want to add the nightly NuGet feed: https://github.com/xamarin/Xamarin.Forms/wiki/Nightly-Builds

**Comment by farr64** [comment]
Thanks for the tip. Makes perfect sense.

I added everything from the nightly feed and I still get errors and warnings. Please see attached file with the report.

Am I missing something else!

Thank you.

[190714_Xappy_errors.txt](https://github.com/davidortinau/Xappy/files/3390802/190714_Xappy_errors.txt)

**Comment by farr64** [comment]
More info (including a file with the details of my configuration) in case it helps. I'll be pleased to keep trying until I get this to work. The prevoious version managed to build and run (and it crashed soon thereafter -- but at least it built).

Thanks.

ps 2019-07-14 at 9 58 26 PM

[190714_Visual_Studio_Mac_details.txt](https://github.com/davidortinau/Xappy/files/3390812/190714_Visual_Studio_Mac_details.txt)

**Pull request merged**
