### PR TITLE
Rebuild LoginPage using CSharpForMarkup

### PR DESCRIPTION
**Pull request by VincentH-Net**
LoginPage built using CSharpForMarkup
1) @rdavisau build initial version [live on Twitch](https://www.twitch.tv/videos/441875218), cleanup afterwards
2) @VincentH-Net cleanup & separate markup, animation logic and DSL.
Add hyperlink using new CSharpForMarkup Span helpers

### CODE REVIEW

**Comment by VincentH-Net** [comment]
@rdavisau I noticed csproj changes LangVersion + MtouchExtraArgs. Should those be in here or is that only for Continuous? You OK with the rest of my changes?

**Comment by rdavisau** [comment]
It's a thing of beauty!  👀

I needed to set LangVersion to use CSharpForMarkup with VS4Mac (maybe VS4Mac defaults to a lower version?). `--enable-repl` is harmless but definitely not required (I should have removed it in 604fac8). 

Nice work!

**Comment by VincentH-Net** [comment]
Thanks @rdavisau! I removed all unneeded changes from sln and csproj files and tested against latest stable VS Win and VS Mac.

I only needed to set language version to latest in the shared project to fix build in VS for Mac; [VS doc](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version) says 

> The C# compiler determines a default language version ... When your project doesn't target a preview framework, the language version used is the latest minor version.

However, apparently VS for Mac defaults to latest major. Setting the language to latest ensures the same behaviour in VS Win and VS Mac.

**Review by davidortinau — APPROVED** [review]
looks great gentlemen, an excellent example for everyone to explore. Thanks!

**Pull request merged**
