### PR TITLE
Remove BorderlessEntryRenderer that was left after cleanup.

### PR DESCRIPTION
**Pull request by Alex-Witkowski**
Fixed iOS build. 

With cleanup a few days ago BorderlessEntry was removed but the renderer was still in iOS project and broke the build.

### CODE REVIEW

**Comment by farr64** [comment]
iOS builds now, but Xappy stops immediately after displaying its blue launch screen.

I have dealt with the usual suspects ("xapping" the .vs, bin and obj directories) without success.

I haven't changed anything and this is the cloned respository directly from GitHub to my Mac.

I have attached a file with the 16 warnings reported during the build.

The head and tail of the installation, In case this helps:

```
/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mlaunch -sdkroot "/Applications/Xcode.app/Contents/Developer" --installdev "~/Documents/Xamarin_solutions/Xappy/Xappy/Xappy.iOS/bin/iPhone/Debug/device-builds/iphone8.1-12.3.1/Xappy.iOS.app" --device ios "--devname=FAR iP6s" --install-progress
Installing application bundle 'com.companyname.Xappy' on 'FAR iP6s'

Installing application bundle 'com.companyname.Xappy' on 'FAR iP6s'
 TransferringPackage - PercentComplete: 10%
 CopyingFile - Path: ~/Documents/Xamarin_solutions/Xappy/Xappy/Xappy.iOS/bin/iPhone/Debug/device-builds/iphone8.1-12.3.1/Xappy.iOS.app/META-INF/
 CopyingFile - PercentComplete: 10%

 . . .

 CreatingStagingDirectory - PercentComplete: 5%
 ExtractingPackage - PercentComplete: 15%
 InspectingPackage - PercentComplete: 20%
 TakingInstallLock - PercentComplete: 20%
 PreflightingApplication - PercentComplete: 30%
 InstallingEmbeddedProfile - PercentComplete: 30%
 VerifyingApplication - PercentComplete: 40%
 CreatingContainer - PercentComplete: 50%
 InstallingApplication - PercentComplete: 60%
 PostflightingApplication - PercentComplete: 70%
 SandboxingApplication - PercentComplete: 80%
 GeneratingApplicationMap - PercentComplete: 90%
Application bundle 'com.companyname.Xappy' installed on 'FAR iP6s'

Upload succeeded.

```

[190721_Xappy_warnings.txt](https://github.com/davidortinau/Xappy/files/3414460/190721_Xappy_warnings.txt)

Thanks.

**Comment by farr64** [comment]
More FYI:

I attempted to include all nightly builds even remotely associated with this issue.

Pease see attached report with specific details: Could not add packages.

Are there any specific packages to include and/or to exclude?

All I'm trying to do is to get **some** consistent state that will build **and** run without gobbling up all of my scarce time, with the objective of using some of the working code as an example of what Xamarin can do.

Thanks for doing all the hard work on the fundamentals.

ps 2019-07-21 at 11 38 03 AM

ps 2019-07-21 at 11 46 47 AM

[190721_Xappy_could_not_add_packages.txt](https://github.com/davidortinau/Xappy/files/3414881/190721_Xappy_could_not_add_packages.txt)

**Comment by Alex-Witkowski** [comment]
Hi @farr64,

for me the iOS build an run works with the configuration Debug | iPhoneSimulator > iPhone XR iOS 12.2 

Not tried it with real device or other configuration. Maybe that helps.

Screenshot 2019-07-21 at 21 48 56

Best Alex 

P.S. If you still have errors it may help if you attach the Application Output besides the Tool Output (build).

**Comment by farr64** [comment]
Hi Alex,

It most certainly helped: Xappy works wonderfully on the simulator. Thanks for the great tip ;-)

Now, if we can only get this baby out of the simulator and into the real world, that would be a giant step for Xumanity.

Almost there, an important step at a time.  

I appreciate all of your work. I know how challenging each step is.

**Comment by farr64** [comment]
Well . . .

I let the simulator run for a few minutes and then the simulator decided to eject Xappy (or perhaps vice versa).

I enclose the crash log. I didn't bother to send it to Apple, so I just copied and pasted and saved it for you.

Thanks.

[190721_Xappy_Simulator_crash.txt](https://github.com/davidortinau/Xappy/files/3415462/190721_Xappy_Simulator_crash.txt)

**Comment by Alex-Witkowski** [comment]
So the native crash log don't help. 
I have fixed one more crash that comes when navigating to about but the PullRequest is currently missing. 
Will see if I can do it today evening (CEST). 

It looks like the iOS Version needs some general love ;)

**Pull request merged**
